name: CI - Cloning project and running tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
    image: mongo:6.0
    ports:
      - 27017:27017

  env: 
      MONGO_URI: ${{secrets.MONGO_URI}}   
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api

  
  steps: // Steps represent a sequence of tasks that will be executed as part of the job

  -name: Checkout repository
  uses: actions/checkout@v3  

  -name: Clone repository Athena Redux Bank
  run: 
     git clone git@github.com:Atenea-Conocimientos/redux-athena-bank.git 

-name: Create .env file in the backend directory
run: echo "MONGO_URI=${{env.MONGO_URI}}" >> redux-athena-bank/backend/.env 
run: echo "JWT_SECRET=${{env.JWT_SECRET}}" >> redux-athena-bank/backend/.env
run: echo "PORT=${{env.PORT}}" >> redux-athena-bank/backend/.env
run: echo "VITE_API_URL=${{env.VITE_API_URL}}" >> redux-athena-bank/backend/.env
