name: CI - Cloning project and running tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
    image: mongo:6.0
    ports:
      - 27017:27017

  env: 
      MONGO_URI: ${{secrets.MONGO_URI}}   
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api
